### PR TITLE
Bump csslint version to 1.0.5

### PR DESCRIPTION
**Pull request by guoliang**
Current used csslint version is very old, and does not handle some new rules and does not handle ignore tag correctly.

### CODE REVIEW

**Comment by jgable** [comment]
I don't use this task anymore so I'm not in a good position to maintain it. Looks like the build is failing, can we at least get that fixed up before I attempt to merge this?

**Comment by guoliang** [comment]
Fixed. Btw will the change also be available in npm repository after merge?

**Comment by guoliang** [comment]
@jgable is it possible for you to merge my pull request?

**Comment by jgable** [comment]
Published as 4.0.0 on npm

**Pull request merged**
