### PR TITLE
Add the ability to define custom CSSLint rules

### LINKED ISSUE #16: Support for custom csslint rules
It is possible to add custom rules to csslint. Is it possible to do this with grunt-lesslint? 

Here are some examples of rules that I would like to add:
https://github.com/drBenway/CSSLint-custom-rules

The author suggests adding these manually to the csslint-node.js file, but I'd prefer to have the rules be pluggable. Otherwise I'd have to fork csslint and grunt-lesslint to do it.

### PR DESCRIPTION
**Pull request by davidparsson**
Fixes #16.

The `rule-loader.coffee` became more complex than i wanted, but at least it's well tested. Do you think I've missed any test cases?

### CODE REVIEW

**Comment by jgable** [comment]
Looks good at first glance, I'd like to give it a more thorough look this evening.

**Comment by jgable** [comment]
I took a look and the tests are really great.  Didn't go to the extent of creating a custom rule or anything but the tests make me feel pretty good about shipping this.

Do you think we should publish this with a major version bump (e.g. `1.2.0`)?

**Comment by jgable** [comment]
I've added you as a collaborator.  I usually put things together into a PR rather than pushing straight to master just so other collaborators/watchers can see what's going on, except for version bumps when publishing.

Also, what is your npm username so I can add you as a publisher?

**Comment by davidparsson** [comment]
Thanks, I'm glad you like it! I think a minor version bump should do, since backwards compatibility is preserved.

I'll do some more manual testing with custom rules within the next few hours to make sure I haven't missed anything. If I don't get back to you soon we're good to go.

My npm username is `david.parsson`.

**Comment by davidparsson** [comment]
The only thing I thought the implementation was missing has been fixed in #68, so I think it's ready for being published.

**Comment by jgable** [comment]
:+1: published as `1.2.0` and added you as an owner on npm.

**Comment by davidparsson** [comment]
Thank you!

**Pull request merged**
