### PR TITLE
Issue #90: Add support for showing lint warnings without failing the grunt task.

### PR DESCRIPTION
**Pull request by mmerriam**
- src changes
  - fix broken tests due to new code.
  - add test cases to verify grunt task pass/fail based on various option settings

### CODE REVIEW

**Comment by davidparsson** [comment]
Thank you very much, this looks very promising to me. I'll try to find some time to take a closer look soon.

One thing I noticed when taking a quick look is that the commit message contains a TODO. Is that still valid? To me it seems like those things are fixed.

**Comment by davidparsson** [comment]
Also, do you think that these changes are to be considered backwards compatible?

**Comment by davidparsson** [comment]
Will rules [defined as errors](https://github.com/CSSLint/csslint/wiki/command-line-interface#--errors) be printed as errors or warnings?

**Comment by mmerriam** [comment]
- The "TODO" was taken care of - I initially broke a bunch of tests, but ran out of time and had to update on another commit. Also, I squashed my commits, to clean things up.

- Good catch on the output - I may have only been showing warnings vs errors on the summary line. I will add the details to each caught issue, so the developer knows which are breaking items.

- I think the changes are backwards compatible (at least I tried to do so). Here are the new permutations:

Case 1 - no options set. Both are defaulted:
```
    //     defaulted value -  failOnWarning: true
    //     defaulted value -  failOnError: true
    // __expectation__ - *any* failed rule will fail the grunt task
    lesslint:
      options:
```

Case 2 - one option set (failOnError). the other is defaulted:
```
    //   defaulted value      -  failOnWarning: true
    //   **configured value -  failOnError: false**
    // __expectation__ - the grunt task will never fail, regardless of broken rule (warning/error)
    lesslint:
      options:
        failOnError: false
```

Case 3 - one option set (failOnWarning). the other is defaulted:
```
    //   **configured value -  failOnWarning: false**
    //   defaulted value      -  failOnError: true
    // __expectation__ - the grunt task will only fail on errors, not warnings
    lesslint:
      options:
        failOnWarning: false
```

Case 4 - both options set:
```
    //   **configured value -  failOnWarning: false**
    //   **configured value -  failOnError: false**
    // __expectation__ - the grunt task will never fail, regardless of broken rule (warning/error)
    lesslint:
      options:
        failOnWarning: false
        failOnError: false
```

Let me know if you think these belong in the README, to clarify for other devs.

Thanks.

**Comment by davidparsson** [comment]
Thanks! I went ahead and verified that a violation of a CSSLint rule configured as an error was count as an error here as well, as expected. Good!

Would you mind adding a spec for that? It could be very similar to the existing spec `issues return code 1, if failOnWarning is set to false, with failed rule errors`, but with a new `.csslintrc` file defining ids as an error: `"ids": 2`. I think it's a good test case, since the only specs where errors is not 0 are specs where the less files contains parse or import errors.

**Comment by davidparsson** [comment]
Never mind, I can write that spec myself in a few minutes.

**Comment by davidparsson** [comment]
Thanks for a nice contribution! I'll run a few more tests and publish this as soon as possible. Probably not until tomorrow, though.

**Comment by jgable** [comment]
:+1: Very nice.  Thanks for the test updates.

**Comment by mmerriam** [comment]
Thanks guys. I appreciate the quick response time.

**Pull request merged**
