### PR TITLE
Let the LessParser use 'options.less' instead 'options'.

### PR DESCRIPTION
**Pull request by mdo2**
This correction makes less options in the task settings are not ignored.

### CODE REVIEW

**Comment by mdo2** [comment]
@davidparsson Please, i need it!

**Comment by davidparsson** [comment]
Thanks for your PR, @mdo2. What's the use case for this change?

**Comment by davidparsson** [comment]
If you need to pass custom arguments to the less compiler you can do that by setting them under `options` today. This for example sets the `globalVars`:

    lesslint:
      all: {
        src: "**/*.less",
        options: {
          globalVars: {
            myVar: "someValue"
          }
        }
      }

**Comment by mdo2** [comment]
Ok, is the truth but then update the docs or accept this PR so the plugin works like expected.
Now when i put something at options.less I assume that this will be pass it to the less compiler.

**Comment by mdo2** [comment]
And another thing is that the plugin get the less task options as default but stores them in options.less so this feature is useless right now.

**Comment by davidparsson** [comment]
I recognize that there is a difference between the documented and the actual behavior, and fixing this according to your PR would be better, but that would also break backwards compatibility.

Can you please clarify your last comment?

**Comment by davidparsson** [comment]
Added a note about the upcoming breaking change in #87

**Comment by davidparsson** [comment]
Published in v3.0.0

**Comment by davidparsson** [comment]
Uhm... it looks like we broke certain areas of the plugin.

**Comment by davidparsson** [comment]
Ok, I found out what is was, and it's just a changed behavior, not a but. Since I now have to configure `lessint.options.less` to modify the LESS configuration, the defaults from `less.options` are no longer present under `lesslint.options.less`, as they were before.

**Comment by mdo2** [comment]
ok, now is perfect. Thank you @davidparsson !

**Pull request merged**
