### PR TITLE
Update node supported version and less

### PR DESCRIPTION
**Pull request by glutentag**
Current version of less is outdated and doesn't support the last features.

### CODE REVIEW

**Comment by milworm** [comment]
Hi @jgable could you please merge this PR and release new version?

**Comment by davidparsson** [comment]
This seems all right to me, but I'm not sure if I have the permissions to make releases. I'll make a try in a few days if @jgable won't.

**Comment by jgable** [comment]
@davidparsson what is your npm username? I can add you as a publisher for this module.

**Comment by davidparsson** [comment]
It seems I'm a collaborator on npm so I'll give publishing a try tomorrow.

**Comment by davidparsson** [comment]
I've just released this as `5.0.0`

**Comment by davidparsson** [comment]
I've just released this as `5.0.0`

**Pull request merged**
